name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.11.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.7'

    - name: Install uv with curl
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh 

    - name: Install make (if not already available)
      run: sudo apt-get install make

    - name: Install black
      run: |
        pip install black

    - name: Install dependencies
      run: |
        make install
      # bash ./runme.sh

    - name: Run tests
      run: |
        source venv/bin/activate
        make test

    # Optional: Linting and formatting checks
    - name: Check code formatting
      run: |
        make format
    
    - name: Lint code
      run: |
        make lint